trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      echo "COSMOS_DB_ENDPOINT=$(COSMOS_DB_ENDPOINT)" >> .env.local
      echo "COSMOS_DB_KEY=$(COSMOS_DB_KEY)" >> .env.local
      echo "COSMOS_DB_NAME=$(COSMOS_DB_NAME)" >> .env.local
    displayName: 'Set environment variables'

  - script: |
      npm run build
    displayName: 'next build'
