trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      echo "COSMOS_DB_ENDPOINT=$(COSMOS_DB_ENDPOINT)" >> $(Pipeline.Workspace)/.env
      echo "COSMOS_DB_KEY=$(COSMOS_DB_KEY)" >> $(Pipeline.Workspace)/.env
      echo "COSMOS_DB_NAME=$(COSMOS_DB_NAME)" >> $(Pipeline.Workspace)/.env
    displayName: 'Set environment variables'

  - script: |
      next build
    displayName: 'next build'
    env:
      COSMOS_DB_ENDPOINT: $(COSMOS_DB_ENDPOINT)
      COSMOS_DB_KEY: $(COSMOS_DB_KEY)
      COSMOS_DB_NAME: $(COSMOS_DB_NAME)
