projects:
  myProject:
    schema: schema.graphql
    extensions:
      endpoints:
        default:
          url: http://localhost:4000/graphql
          headers:
            Authorization: Bearer YOUR_AUTH_TOKEN
